(library
 (name qam_rewrite)
 (wrapped false)
 (libraries grammar qam_ast)
 (modules checkEquivalence interpreter chemistry compile sim))

(executable
 (name main)
 (libraries qam_rewrite)
 (modules main))

(executable
 (name chem_main)
 (libraries qam_rewrite)
 (modules chem_main))

(test
 (name testCase)
 (modules testCase)
 (deps (glob_files examples/qam/*.qam))
 (libraries qam_rewrite ounit2))
